on:
  push:
    branches:
      - master
name: Docker Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Docker Build
        run: docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}:latest .

      - name: Docker Login
        run: docker login docker.pkg.github.com -u github-actions -p ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Tag
        run: docker tag docker.pkg.github.com/${REPOSITORY}:latest docker.pkg.github.com/${REPOSITORY}:${GITHUB_SHA}

      - name: Docker Push
        run: docker push docker.pkg.github.com/${REPOSITORY}

